#!/usr/bin/env python3
"""Generate the compiled Swift catalog from Go's embedded catalog (no extra bundle)."""
import json
from pathlib import Path
import sys
import re
root = Path(__file__).resolve().parents[1]
catalog = json.loads((root / 'internal/i18n/catalog.json').read_text())
entries = '\n'.join('        '+json.dumps(key, ensure_ascii=False)+': '+json.dumps(value, ensure_ascii=False)+',' for key,value in sorted(catalog.items()))
source = '// Generated by scripts/generate-localizations.py; do not edit.\nimport Foundation\n\nextension L10n {\n    static let korean: [String: String] = [\n'+entries+'\n    ]\n}\n'
path = root / 'helpers/Sources/HelperCore/LocalizationCatalog.swift'
if '--check' in sys.argv:
    if not path.exists() or path.read_text() != source:
        sys.exit('Localization catalog is stale; run python3 scripts/generate-localizations.py')
else:
    path.write_text(source)

# Detect a new call site that forgot to add its translation.
for base, glob, pattern in [('helpers/Sources', '*.swift', r'L10n\.text\("((?:[^"\\\n]|\\.)*)"'), ('internal', '*.go', r'i18n\.Text\("((?:[^"\\\n]|\\.)*)"'), ('cmd', '*.go', r'i18n\.Text\("((?:[^"\\\n]|\\.)*)"')]:
    for source_file in (root / base).rglob(glob):
        for key in re.findall(pattern, source_file.read_text()):
            key = json.loads('"' + key + '"')
            if key not in catalog:
                sys.exit(f'Missing translation in {source_file}: {key}')

# Also reject direct UI literals, the source of mixed-language menus.
import subprocess
subprocess.run([sys.executable, str(root / "scripts/check-ui-localization.py")], check=True)
